# Generated by Django 4.1.5 on 2023-01-16 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FundoImobiliário',
            new_name='FundoImobiliario',
        ),
    ]
