# Generated by Django 4.1.5 on 2023-01-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_fundoimobiliário_fundoimobiliario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundoimobiliario',
            name='vacancia_financeira',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='fundoimobiliario',
            name='vacancia_fisica',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
